import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import client from "../apollo-client";
import { gql } from "@apollo/client";

export async function getServerSideProps() {
  const { data } = await client.query({
    query: gql`
        query($name: String, $sku: String, $minPrice: Int, $maxPrice: Int, $vendorId: ID) {
            products(filters: { name: $name, sku: $sku, minPrice: $minPrice, maxPrice: $maxPrice, vendorId: $vendorId }) {
                _id
                name
                sku
                quantity
                price
                vendor {
                    name
                }
            }
        }`
  });

  return {
    props: {
      products: data.products
    }
  }
}

export default function Home({ products }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
      </main>
        <div className={styles.grid}>
            {products.map((product) => (
                <div key={product._id} className={styles.card}>
                    <h3>{product.name}</h3>
                    <p>
                        {product.sku} - {product.price}
                    </p>
                </div>
            ))}
        </div>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
